version = 1

exclude_patterns = [
    ".github/**",
    ".idea/**",
    "sample/**",
    "Makefile"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/sampgo/cli"

[[transformers]]
name = "gofmt"
enabled = true