# sample sampgo.toml file.

## notes:
# all globals go under the global table.
# output can contain the file extension if wanted.

[global]
sampctl = false

[author]
user = "alextwothousand"
repo = "cli"

[package]
name = "grandlarc"

input = "gofile.go"
output = "libname.so"