name: freebsd

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:

  amd64:
    runs-on: ubuntu-latest
    env:
      GOOS: openbsd
      GOARCH: amd64
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Get dependencies
      run: go get -u

    - name: Build
      run: go build -v -o sampgo_amd64 main.go

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        # Artifact name
        name: sampgo_amd64
        # A file, directory or wildcard pattern that describes what to upload

        path: .

        # how long the files will be stored on github's servers
        retention-days: 90

  i386:
    runs-on: ubuntu-latest
    env:
      GOOS: openbsd
      GOARCH: 386
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Get dependencies
      run: go get -u

    - name: Build
      run: go build -v -o sampgo_386 main.go

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        # Artifact name
        name: sampgo_386
        # A file, directory or wildcard pattern that describes what to upload

        path: .

        # how long the files will be stored on github's servers
        retention-days: 90

  arm64:
    runs-on: ubuntu-latest
    env:
      GOOS: openbsd
      GOARCH: arm64
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Get dependencies
      run: go get -u

    - name: Build
      run: go build -v -o sampgo_arm64 main.go

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        # Artifact name
        name: sampgo_arm64
        # A file, directory or wildcard pattern that describes what to upload

        path: .

        # how long the files will be stored on github's servers
        retention-days: 90

  i386:
    runs-on: ubuntu-latest
    env:
      GOOS: openbsd
      GOARCH: arm
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Get dependencies
      run: go get -u

    - name: Build
      run: go build -v -o sampgo_arm main.go

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        # Artifact name
        name: sampgo_arm
        # A file, directory or wildcard pattern that describes what to upload

        path: .

        # how long the files will be stored on github's servers
        retention-days: 90